export const BaseCabinet="bc";
export const WallCabinet="wc";
export const WallSnapBoxes="Wall Snapbox";
export const BaseSnapBoxes="Base Snapbox"
export const WallSnapPoints="wall_snapPoints";
export const BaseSnapPoints="base_snapPoints";
export const WALL_GEOMETRY = "Wall";
export const QR_CODE_ID = 'qrCode'; //for UI
export const DefaultCamera="Cam1";
export const Dimensions_GEO="Dimensions";
export const Dimensions_Text="Dimesnion Text";
export const PreviewScene="Preview Scene";
export const PreviewShutters="Preview Shutters";
export const Units="Imperial Units"